name: Justin Adkins
email: justin.adkins@protonmail.com
location: Columbus, OH USA
github_username: jmadkins
twitter_username: hijustinadkins
about_me: >-
  Developer, small business owner, lover of Lord of the Rings, cats, and all things politics.
  Started with C# but have fallen in love with ruby.
baseurl: ""
url: "https://adkinss.io"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
