title: Justin Adkins
location: Columbus, OH USA
about_me: >-
  Developer, cat and fish dad, business owner, lover of Lord of the Rings,
  Star Wars, and all things politics. Started with C# but have fallen in love with ruby.
baseurl: ""
url: https://adkins.dev
emails:
  - jadkins@hey.com
networks:
  - icon: github
    url: https://github.com
    username: jmadkins
  - icon: linkedin
    url: https://www.linkedin.com/in
    username: jmadkins
  - icon: stack-overflow
    url: https://stackoverflow.com/users/2247108
    username: justin-adkins
  - icon: twitter
    url: https://twitter.com
    username: hijustinadkins
jobs:
  - position: Owner
    company: MythCoders
    url: https://www.mythcoders.com
  - position: Executive Director
    company: Ecclesia
    url: https://www.ecclesia.vote
  - position: Software Developer
    company: CoverMyMeds
    url: https://www.covermymeds.com/
  - position: Former candidate for Ohio State Senate
    company: Adkins For Ohio
    url: https://www.adkinsforohio.com

# Build settings
markdown: kramdown
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
