server {
  listen 80;

  # Configure URL rewrites
  rewrite ^/work-history$ /experience permanent;

  # Only needed if there's no CDN in front
  gzip on;

  # Turn on SSI with etags and long values
  ssi on;
  ssi_last_modified on;
  ssi_value_length 1024;

  # All web accessible files live here
  root /site/public;

  # Map error pages
  error_page 401 /_errors/401.html;
  error_page 404 /_errors/404.html;
  error_page 500 502 503 504 /_errors/500.html;

  # Folders starting with _ are not publicly accessible
  location ~ ^/_ {
    internal;
  }

  # Make /up look first for /up.html then /up/index.html
  location / {
    try_files $uri $uri.html $uri/index.html =404;
  }

  # Cache static assets, revalidating against the ETag on each use
  location ~* \.(?:ico|css|js|gif|jpe?g|png|webp)$ {
    add_header Cache-Control "no-cache";
  }
}
